const Ziggy = {"url":"http:\/\/ruma-web.test","port":null,"defaults":{},"routes":{"login":{"uri":"login","methods":["GET","HEAD"]},"logout":{"uri":"logout","methods":["POST"]},"password.request":{"uri":"forgot-password","methods":["GET","HEAD"]},"password.reset":{"uri":"reset-password\/{token}","methods":["GET","HEAD"]},"password.email":{"uri":"forgot-password","methods":["POST"]},"password.update":{"uri":"reset-password","methods":["POST"]},"user-profile-information.update":{"uri":"user\/profile-information","methods":["PUT"]},"user-password.update":{"uri":"user\/password","methods":["PUT"]},"password.confirm":{"uri":"user\/confirm-password","methods":["GET","HEAD"]},"password.confirmation":{"uri":"user\/confirmed-password-status","methods":["GET","HEAD"]},"two-factor.login":{"uri":"two-factor-challenge","methods":["GET","HEAD"]},"two-factor.enable":{"uri":"user\/two-factor-authentication","methods":["POST"]},"two-factor.disable":{"uri":"user\/two-factor-authentication","methods":["DELETE"]},"two-factor.qr-code":{"uri":"user\/two-factor-qr-code","methods":["GET","HEAD"]},"two-factor.recovery-codes":{"uri":"user\/two-factor-recovery-codes","methods":["GET","HEAD"]},"graphql-playground":{"uri":"graphql-playground","methods":["GET","HEAD"]},"graphql":{"uri":"graphql","methods":["GET","POST","HEAD"]},"home":{"uri":"home","methods":["GET","HEAD"]},"profile":{"uri":"my-profile","methods":["GET","HEAD"]},"settings.updateAccountInfo":{"uri":"settings\/update-account-information","methods":["POST"]},"settings.updatePassword":{"uri":"settings\/update-password","methods":["POST"]},"settings.toggleOTP":{"uri":"settings\/toggle_otp","methods":["GET","HEAD"]},"settings.toggle2fa":{"uri":"settings\/toggle_2fa","methods":["GET","HEAD"]},"settings.recovery_code":{"uri":"settings\/generate_recovery_code","methods":["GET","HEAD"]},"settings.sessions_browser":{"uri":"settings\/logout_other_sessions_browser","methods":["POST"]},"companies.index":{"uri":"companies","methods":["GET","HEAD"]},"companies.create":{"uri":"companies\/create","methods":["GET","HEAD"]},"companies.store":{"uri":"companies","methods":["POST"]},"companies.show":{"uri":"companies\/{company}","methods":["GET","HEAD"]},"companies.edit":{"uri":"companies\/{company}\/edit","methods":["GET","HEAD"]},"companies.update":{"uri":"companies\/{company}","methods":["PUT","PATCH"]},"companies.destroy":{"uri":"companies\/{company}","methods":["DELETE"]}}};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    for (let name in window.Ziggy.routes) {
        Ziggy.routes[name] = window.Ziggy.routes[name];
    }
}

export { Ziggy };
