<?php

#Job status
const JOB_STATUS_ON_LEAVE = 'ON-LEAVE';
const JOB_STATUS_TERMINATED = 'TERMINATED';
const JOB_STATUS_IN_ACTIVE = 'IN-ACTIVE';
const JOB_STATUS_ACTIVE = 'ACTIVE';
const JOB_STATUS_SUSPENDED = 'SUSPENDED';

#Employee status
const EMPLOYMENT_STATUS_PROBATION_PERIOD = 'PROBATION-PERIOD';
const EMPLOYMENT_STATUS_PART_TIME = 'PART-TIME';
const EMPLOYMENT_STATUS_FULL_TIME = 'FULL-TIME';

