<?php


namespace App\Exceptions;


use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;
class ApiExceptionHandler extends ExceptionHandler
{

    /**
     * ApiExceptionHandler constructor.
     * @param mixed $app
     * @param \Illuminate\Config\Repository|\Illuminate\Contracts\Foundation\Application|mixed $Config
     * @param \Illuminate\Config\Repository|\Illuminate\Contracts\Foundation\Application|mixed $Config1
     */
    public function __construct(ExceptionHandler $handler, $Config, $Config1)
    {

    }

    public function render($request, Throwable $e)
    {
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }

}
